# Generated by Django 5.2.14 on 2026-05-14 18:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0002_remove_bow_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('location', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], max_length=20)),
                ('session_type', models.CharField(choices=[('free_practice', 'Free practice')], default='free_practice', max_length=30)),
                ('distance_m', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('arrow_count', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('bow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='equipment.bow')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
