# Generated by Django 5.2.14 on 2026-05-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_sessions', '0002_alter_session_bow'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='next_focus',
            field=models.TextField(blank=True),
        ),
    ]
