# Generated by Django 5.2.14 on 2026-06-13 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_sessions', '0004_rename_arrow_count_add_scoring_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='fatigue',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Very low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very high')], null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='nutrition',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Very poor'), (2, 'Poor'), (3, 'OK'), (4, 'Good'), (5, 'Very good')], null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='physical_sensations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='session',
            name='sleep_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AddField(
            model_name='session',
            name='sleep_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='session',
            name='stress',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Very low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very high')], null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='temperature_celsius',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='time_of_day',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('day', 'Day'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='weather',
            field=models.CharField(blank=True, choices=[('sunny', 'Sunny'), ('partly_cloudy', 'Partly cloudy'), ('overcast', 'Overcast'), ('rainy', 'Rainy')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='wind_direction',
            field=models.CharField(blank=True, choices=[('from_left', 'From left'), ('from_right', 'From right'), ('from_front', 'From front'), ('from_back', 'From back'), ('from_front_left', 'From front-left'), ('from_front_right', 'From front-right'), ('from_back_left', 'From back-left'), ('from_back_right', 'From back-right')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='wind_force',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Calm'), (2, 'Light'), (3, 'Medium'), (4, 'Strong'), (5, 'Very strong')], null=True),
        ),
    ]
