# Generated by Django 5.2.14 on 2026-05-09 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('olympic_recurve', 'Olympic Recurve')], max_length=50)),
                ('draw_weight_lbs', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OlympicBowSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riser', models.CharField(blank=True, max_length=200)),
                ('limbs', models.CharField(blank=True, max_length=200)),
                ('arrow_rest', models.CharField(blank=True, max_length=200)),
                ('sight', models.CharField(blank=True, max_length=200)),
                ('main_stabilizer', models.CharField(blank=True, max_length=200)),
                ('extender', models.CharField(blank=True, max_length=200)),
                ('side_stabilizers', models.CharField(blank=True, max_length=200)),
                ('v_bar', models.CharField(blank=True, max_length=200)),
                ('clicker', models.CharField(blank=True, max_length=200)),
                ('button', models.CharField(blank=True, max_length=200)),
                ('bow', models.OneToOneField(limit_choices_to={'type': 'olympic_recurve'}, on_delete=django.db.models.deletion.CASCADE, related_name='olympic_setup', to='equipment.bow')),
            ],
        ),
    ]
