# Generated by Django 5.2.14 on 2026-05-09 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bow',
            name='owner',
        ),
    ]
