# Generated by Django 5.2.14 on 2026-05-16 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_remove_bow_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bow',
            name='length_inches',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(80)], verbose_name='Bow length in inches'),
        ),
    ]
