# Generated by Django 5.2.14 on 2026-06-04 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions_per_page', models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
            },
        ),
    ]
